apiVersion: v1
kind: Service
metadata:
  name: kus-kus
spec:
  selector:
    app: kus-kus
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kus-kus
spec:
  selector:
    matchLabels:
      app: kus-kus
  replicas: 1
  template:
    metadata:
      labels:
        app: kus-kus
    spec:
      containers:
        - name: kus-kus
          image: blink182u2/kus-kus:0.0.1
          env:
            - name: SPRING_ELASTICSEARCH_URIS
              value: https://vpc-kus-kus-search-g5p77gomzoxh4k6dfond2ib754.me-south-1.es.amazonaws.com:443
            - name: SPRING_ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bot-secret
                  key: elastic-username
            - name: SPRING_ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bot-secret
                  key: elastic-password
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
            limits:
              cpu: 300m
              memory: 500Mi
